In [1]:
# Standard imports
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Add mavenn to path
import sys
path_to_mavenn_local = '/Users/jkinney/github/mavenn'
sys.path.insert(0,path_to_mavenn_local)

# Load mavenn and check path
import mavenn
mavenn.__path__

['/Users/jkinney/github/mavenn/mavenn']

In [2]:
# Load model
ge_model = mavenn.load('20.08.26_load_models_for_JBK/model_files/gaussian_GB1_model')

# Set wt sequence
wt_seq = 'QYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYDDATKTFTVTE'

# Comptue effects
mat_df = ge_model.get_1pt_effects(wt_seq=wt_seq, out_format="matrix")
mat_df.head()

/Users/jkinney/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Users/jkinney/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)

,A,C,D,E,F,G,H,I,K,L,M,N,P,Q,R,S,T,V,W,Y
pos,,,,,,,,,,,,,,,,,,,,
0,0.665872,0.481028,0.440047,0.507864,0.694335,0.571362,0.557210,0.592041,0.625925,0.626588,0.639278,0.542951,0.615656,0.000000,0.692714,0.595395,0.624055,0.551604,0.635700,0.634407
1,-0.175843,-0.061745,-1.209723,-1.195648,0.497363,-0.902313,0.376042,-0.142086,-0.908762,0.177971,0.053939,-0.701270,-0.861779,-0.540745,-0.756277,-0.488206,-0.641750,-0.232460,0.540797,0.000000
2,0.339716,0.363056,0.106384,0.170474,0.410854,0.213318,0.382038,0.462981,0.000000,0.626056,0.479805,0.340424,-1.061957,0.425134,0.533913,0.351455,0.431311,0.487615,0.461641,0.391828
3,0.209671,0.358876,-2.613432,-1.795794,0.198946,-0.282179,-0.453318,-0.132050,-1.332428,0.000000,0.133827,-0.314039,-1.967560,-0.516624,-1.552350,-0.184894,-0.158808,0.317575,-0.560478,-0.506025
4,0.329486,0.388905,0.189605,0.464806,0.590217,0.359278,0.504861,0.000000,0.500259,0.619596,0.395776,0.399140,-2.694215,0.481461,0.502602,0.325962,0.465974,0.491370,0.544348,0.625398

In [3]:
# Comptue effects
mat_df = ge_model.get_1pt_effects(wt_seq=wt_seq, out_format="tidy")
mat_df.head()

/Users/jkinney/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)

,pos,wt_char,mut_char,seq,phi,dphi
name,,,,,,
WT,-1,,,QYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYDD...,0.066744,0.000000
Q0A,0,Q,A,AYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYDD...,0.732616,0.665872
Q0C,0,Q,C,CYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYDD...,0.547772,0.481028
Q0D,0,Q,D,DYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYDD...,0.506791,0.440047
Q0E,0,Q,E,EYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYDD...,0.574608,0.507864

In [ ]:
# from mavenn.src.error_handling import check, handle_errors
# from mavenn.src.validate import validate_alphabet
# from mavenn.src.utils import get_1pt_variants

# @handle_errors
# def get_1pt_effects(model, wt_seq, out_format="matrix"):
#     """
        
#     parameters
#     ----------
    
#     model: (mavenn.Model)
#         A MAVE-NN model.

#     wt_seq: (str)
#         The wild-type sequence.

#     out_format: ("matrix" or "tidy")
#         If matrix, a 2D matrix of dphi values is
#         returned, with characters across columns and
#         positions across rows. If "tidy", a tidy
#         dataframe is returned that additionally lists
#         all variant sequences, phi values, etc.
    
#     returns
#     -------
    
#     out_df: (pd.DataFrame)
#         Dataframe containing dphi values and other 
#         information.
#     """
    
#     # Get all 1pt variant sequences
#     df = get_1pt_variants(wt_seq=wt_seq, alphabet=model.alphabet, include_wt=True)
#     x = df['seq'].values
    
#     # Compute dphi values
#     df['phi'] = ge_model.x_to_phi(x)
#     df['dphi'] = df['phi'] - df['phi']['WT']
    
#     if out_format=="tidy":
#         mut_df = df
#     elif out_format=="matrix":
#         # Keep only non-wt rows
#         ix = (df.index != 'WT')
#         tmp_df = df[ix]
    
#         # Pivot matrix and return
#         mut_df = tmp_df.pivot(index='pos',columns='mut_char',values='dphi')
#         mut_df.fillna(0, inplace=True)
#         mut_df.columns.name=None
#     else:
#         mut_df = None
#         check(out_format in ["tidy","matrix"],
#               f"out_format={out_format}; must be 'tidy' or 'matrix'.")
        
#     return mut_df